language: java

dist: focal

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  include:
    - jdk: openjdk15
    - jdk: openjdk12
    - jdk: openjdk11
    # Java 9 cannot build the project: https://github.com/gradle/gradle/issues/15267
    # - jdk: openjdk9

script:
  - ./gradlew build integrationTest -s --info

notifications:
  email: false
