language: java

dist: focal

services:
  - docker

matrix:
  include:
    - jdk: openjdk15
    - jdk: openjdk12
    - jdk: openjdk11
    - jdk: openjdk9
    - jdk: openjdk8

script:
  - mvn clean install

notifications:
  email: false
